language: node_js
node_js:
- 12.13.1
notifications:
  email: false
script:
- npm run build
before_deploy:
- cd dist
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIA2CQO232KJVHWUSMS
  secret_access_key:
    secure: QZzoxUmtv3LWp3Z8WWLVRGzoJZqHqLpv8DtgGL9Vj/Wx5wrHdHALjq2NeIimAg7v130Ehc/j03ST2kr/ioQ2S+NsufCA0xYDELo7mf05ETCuZnVpQ+bYOpU3vAEVXLvDp+itGiiafnWCoX+dLODmVW2xzpoU9tdkbV2pdG6bErhLEtJh6LMTaNuqm9uYIHyVFb034LILs3hhbX2/W4vlqfa1nHPMF+MLp2+zTv/Vrx6B+6EtzNH1ol6/CcOMBcAJrOagQs1ZCMv5FFjyR9vk1Gk3VPl35fI/UioxR1BhEcpuIqp3YX7+Fjc9ByuSwterPRZt0F+Skc95ihK0IKg61jf5ExXLMHtFdsyB3Mo/vTh1KgCm0UKP2zCth2BmHaUL+uFBMCUOlgyDR5FbckeSNE/1WMfiIPYHqEzDCT0XbcLtSMat4Ts4E3dWjMfcoIsav4UEdOmzq7KG0q9kZu48H/Zs+72gSZXDNtk8W+zXo6+zvqf5GxLTo2eqvCVZ4Qh7fwp8yxYrgPRlLY+rY9e0CxbrRQ23DPh4hqTqf5wXiLcfJJOMqTXsVKcWZA5wVgZVm90b/DUeuBXS35mX/1jIXCpixzEJ317gyAfJMerklEpXuRXG0XpxUHVIig65LQRRBaA29+1+ql0SLM9QtJ8sO0pLIc0SxDaom4iucV3YoSo=
  bucket: com.shepherdjerred.shepherdjerred
