language: node_js
node_js:
- 12.13.1
notifications:
  email: false
script:
- npm run build
before_deploy:
- cd dist
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIA2CQO232KOVBT45FC
  secret_access_key:
    secure: HoP2GwSsTqJZ5qOvpw7vDMR0SuHAdCeOUmvMrFMRGsNFbzi50zHHflspvFKRJg1s5xyPoxDw10dTAwlXT1IKkSHrRNKxfFNXx8gYSbrn9u0pf6vevpbbjX19H3kL86+7SzRmPBMb2tu0miGIQqP6opDnng6T0zKyOFdjZxJ1rDe/X0EArmHz7dmUwE5toA24KTabtskJdL2f1PRRT8BW3Y7MVRv8AGrsLyBbr+ooOFJuAjysIpg+63C6osc8RnJNEW3eQzKqrvEoBvvC0lZTUkNi+gMmmgYtXpg+BAUV6bYbz27KdVjEA1IEIyj+81HBXlApEN08fKgLjHXU+/DjJKR65T8CpMpOuourJD1fwWANyUB32MoDBPc7gPUaw5djCpyMYwZpemcYF9wunaWO1xQjqN3KVzDfSe2F1v5BgA1ZJwfFJ+3Jw3hUl5iOLCwYhGY5IIqFibzrmrb03JaZpSp4pYNe28T2hdXk6YVkGF8FCYn1FmMjILHqZkCzwZ0kDj8Onq9aSRSPhybKDPzbNLTGdeZBefz5Id6EBZjG/G+/X67v1EfXiTV9xSGHBQnHzsjgS/yc/N4BoeE1zu3VblDlBeBXA3/NtPit4MhT2LJJQC8cBkzdQ5k/Qb5f6i8bqiaSE1rmIm/rEpnKK9k0LO0JU4PCIzAooINlQhkq1bQ=
  bucket: com.shepherdjerred.shepherdjerred
